---
- name: Update apt cache and install Java
  apt:
    name:
      - default-jre
    state: present
    update_cache: yes

- name: Create kafka group
  group:
    name: kafka
    state: present

- name: Create kafka user
  user:
    name: kafka
    state: present
    group: kafka

- name: Create installation directory
  file:
    path: "{{ kafka_dir }}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka

- name: Check if kafka directory is empty
  command: "ls {{ kafka_dir }}"
  register: kafka_dir_content

- name: Download kafka and unzip
  unarchive:
    src: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    dest: "{{ kafka_dir }}"
    mode: 0755
    remote_src: yes
    owner: kafka
    group: kafka
  when: kafka_dir_content.stdout == ""

- name: Move all the files to parent Directory
  shell:
    mv {{ kafka_dir }}/kafka_*/* {{ kafka_dir }}/.
  when: kafka_dir_content.stdout == ""

- name: Update the log path
  replace:
    path: "{{ kafka_dir }}/config/server.properties"
    regexp: 'log.dirs=(.+)'
    replace: 'log.dirs={{ kafka_dir }}/logs'
    backup: yes

- name: Update the Java heap size for kafka
  replace:
    path: "{{ kafka_dir }}/bin/kafka-server-start.sh"
    regexp: 'export KAFKA_HEAP_OPTS=(".+")'
    replace: 'export KAFKA_HEAP_OPTS="-Xmx520M -Xms520M"'
    backup: yes

- name: Create zookeeper service
  template:
    src: "zookeeper.service.j2"
    dest: /etc/systemd/system/zookeeper.service
    mode: 0755

- name: Create kafka service
  template:
    src: "kafka.service.j2"
    dest: /etc/systemd/system/kafka.service
    mode: 0755

- name: Start services
  tags: startservices
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - "kafka"
    - "zookeeper"

- name: Validating if zookeeper is up and listening on port 2181
  wait_for:
    host: localhost
    port: 2181
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"

- name: Validating if Kafka is up and listening on port 9092
  wait_for:
    host: localhost
    port: 9092
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"

- name: Create topics
  shell: "{{ kafka_dir }}/bin/kafka-topics.sh --if-not-exists --create --topic {{ item }} --bootstrap-server localhost:9092"
  with_items: "{{ create_topics }}"
